### PR TITLE
Update ttl.markdown

### PR DESCRIPTION
**Pull request by KMASubhani**
fixed return values for does not exists key v. never expiring key via TTL command

### CODE REVIEW

**Comment by badboy** [comment]
Hi @KMASubhani, I am the current maintainer of try.redis.io
Can you please re-submit this pull-request over at [badboy/try.redis](https://github.com/badboy/try.redis/) so I can merge it? Thanks.

**Comment by alexmchale** [comment]
Hi @badboy - I should have done this sooner, but I've made you a collaborator on my fork. I think that should enable you to do what you need to manage this. Let me know if I can help.

**Comment by KMASubhani** [comment]
@badboy I've forked and resubmitted the pull request to your branch.

**Comment by badboy** [comment]
Thanks, @KMASubhani, will merge it ASAP.
Thanks @alexmchale, I will update this repo to point to the new one (and will add some notes to the readme over there as well)

**Pull request closed without merging**
